version: '3.9'

services:
  msbtrust_app:
    container_name: msbtrust_app
    image: msb_trust_v1
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://msbtrust_db:5432/msbtrust
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
    depends_on:
      - msbtrust_db

  msbtrust_db:
    image: postgres:16
    container_name: msbtrust_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: msbtrust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/static/data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./src/main/resources/static/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata: {}
